// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5TqgURPi123g4RSuOCMp75SsVDKYd_Vk',
    appId: '1:840833979473:web:9fd75f8c62e92354bd1470',
    messagingSenderId: '840833979473',
    projectId: 'compare-app-b5c2f',
    authDomain: 'compare-app-b5c2f.firebaseapp.com',
    storageBucket: 'compare-app-b5c2f.appspot.com',
    measurementId: 'G-HZ3B244NFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD877ZV-Y2X4l-KFxpAfrq0BzsF_Fwiaho',
    appId: '1:840833979473:android:223f884f3cf5b91dbd1470',
    messagingSenderId: '840833979473',
    projectId: 'compare-app-b5c2f',
    storageBucket: 'compare-app-b5c2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATGlceDmXda6p40WuZswCLiB46s0WGV_8',
    appId: '1:840833979473:ios:90940767af50a220bd1470',
    messagingSenderId: '840833979473',
    projectId: 'compare-app-b5c2f',
    storageBucket: 'compare-app-b5c2f.appspot.com',
    androidClientId: '840833979473-2g2khipa94ugmnd9j9cqu4uficqerna1.apps.googleusercontent.com',
    iosClientId: '840833979473-ic23jpkuitht3257epmqq31oal0thh6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.compareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATGlceDmXda6p40WuZswCLiB46s0WGV_8',
    appId: '1:840833979473:ios:8b1cc5e4e3a78198bd1470',
    messagingSenderId: '840833979473',
    projectId: 'compare-app-b5c2f',
    storageBucket: 'compare-app-b5c2f.appspot.com',
    androidClientId: '840833979473-2g2khipa94ugmnd9j9cqu4uficqerna1.apps.googleusercontent.com',
    iosClientId: '840833979473-vikl7brsnfmpqc7o004isht0jfgpk7f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.compareApp.RunnerTests',
  );
}
